# Generated by Django 4.2 on 2023-04-28 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0004_appointment_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('service', 'appointment_date', 'customer')},
        ),
    ]
