# Generated by Django 4.2 on 2023-04-28 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_site', '0005_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='duration',
        ),
    ]
