# Generated by Django 4.2 on 2023-04-24 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='name',
            new_name='username',
        ),
    ]
