# Generated by Django 4.2 on 2023-04-25 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_customuser_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
